USE [master]
GO
/****** Object:  Database [RCPartsPlus]    Script Date: 3/1/2020 8:15:04 PM ******/
CREATE DATABASE [RCPartsPlus]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RCPartsPlus', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\RCPartsPlus.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RCPartsPlus_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\RCPartsPlus_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [RCPartsPlus] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RCPartsPlus].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [RCPartsPlus] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [RCPartsPlus] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [RCPartsPlus] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [RCPartsPlus] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [RCPartsPlus] SET ARITHABORT OFF 
GO
ALTER DATABASE [RCPartsPlus] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [RCPartsPlus] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [RCPartsPlus] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [RCPartsPlus] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [RCPartsPlus] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [RCPartsPlus] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [RCPartsPlus] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [RCPartsPlus] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [RCPartsPlus] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [RCPartsPlus] SET  ENABLE_BROKER 
GO
ALTER DATABASE [RCPartsPlus] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [RCPartsPlus] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [RCPartsPlus] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [RCPartsPlus] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [RCPartsPlus] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [RCPartsPlus] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [RCPartsPlus] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [RCPartsPlus] SET RECOVERY FULL 
GO
ALTER DATABASE [RCPartsPlus] SET  MULTI_USER 
GO
ALTER DATABASE [RCPartsPlus] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [RCPartsPlus] SET DB_CHAINING OFF 
GO
ALTER DATABASE [RCPartsPlus] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [RCPartsPlus] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [RCPartsPlus] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'RCPartsPlus', N'ON'
GO
ALTER DATABASE [RCPartsPlus] SET QUERY_STORE = OFF
GO
USE [RCPartsPlus]
GO
/****** Object:  Table [dbo].[CustomerInfo]    Script Date: 3/1/2020 8:15:05 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CustomerInfo](
	[AccountID] [int] NOT NULL,
	[NameFirst] [varchar](20) NOT NULL,
	[NameLast] [varchar](30) NOT NULL,
	[Zipcode] [varchar](10) NOT NULL,
	[Address] [varchar](30) NULL,
PRIMARY KEY CLUSTERED 
(
	[AccountID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Inventory]    Script Date: 3/1/2020 8:15:05 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Inventory](
	[PartNumber] [int] NOT NULL,
	[Weight] [int] NOT NULL,
	[PartName] [varchar](100) NOT NULL,
	[GroundOnly] [varchar](3) NULL,
	[Price] [money] NULL,
PRIMARY KEY CLUSTERED 
(
	[PartNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Invoice]    Script Date: 3/1/2020 8:15:05 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Invoice](
	[InvoiceID] [int] NOT NULL,
	[OrderDate] [datetime] NULL,
	[AccountID] [int] NOT NULL,
	[ShipID] [int] NOT NULL,
	[OrderTotal] [money] NULL,
PRIMARY KEY CLUSTERED 
(
	[InvoiceID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[OrderDetails]    Script Date: 3/1/2020 8:15:05 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OrderDetails](
	[InvoiceID] [int] NOT NULL,
	[OrderNumber] [int] NOT NULL,
	[PartNumber] [int] NOT NULL,
	[NumberOfItems] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[InvoiceID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ShippingDetails]    Script Date: 3/1/2020 8:15:05 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ShippingDetails](
	[ID] [int] NOT NULL,
	[Name] [varchar](20) NOT NULL,
	[ShippingMode] [varchar](10) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Zipcode]    Script Date: 3/1/2020 8:15:05 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Zipcode](
	[Zipcode] [varchar](10) NOT NULL,
	[City] [varchar](30) NOT NULL,
	[State] [varchar](2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Zipcode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [RCPartsPlus] SET  READ_WRITE 
GO
